#!/bin/sh
[ -d /dev ] || mkdir -m 0755 /dev
[ -d /proc ] || mkdir -m 0755 /proc
[ -d /sys ] || mkdir -m 0755 /sys
echo "Mounting filesystems."
mount -a
mkdir /dev/pts
mount /dev/pts

sysctl -p

exec /sbin/init
